/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_grid_free: (a: number, b: number) => void;
export const grid_add_col_group: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const grid_add_row_group: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const grid_cell_count: (a: number) => number;
export const grid_cell_screen_rect: (a: number, b: number, c: number) => [number, number];
export const grid_clear_cell: (a: number, b: number, c: number) => void;
export const grid_edit: (a: number, b: number, c: number) => void;
export const grid_edit_col: (a: number) => number;
export const grid_edit_row: (a: number) => number;
export const grid_end_col_resize: (a: number) => void;
export const grid_get_cell_text: (a: number, b: number, c: number) => [number, number];
export const grid_get_scroll_x: (a: number) => number;
export const grid_get_scroll_y: (a: number) => number;
export const grid_group_count: (a: number) => number;
export const grid_hit_test: (a: number, b: number, c: number) => [number, number];
export const grid_is_resizing: (a: number) => number;
export const grid_load_cells_json: (a: number, b: number, c: number) => void;
export const grid_load_pivot_json: (a: number, b: number, c: number) => void;
export const grid_move_selection: (a: number, b: number, c: number) => void;
export const grid_new: (a: number, b: number) => number;
export const grid_remove_group: (a: number, b: number) => void;
export const grid_render_frame: (a: number) => [number, number];
export const grid_scroll_by: (a: number, b: number, c: number) => void;
export const grid_sel_col: (a: number) => number;
export const grid_sel_row: (a: number) => number;
export const grid_select: (a: number, b: number, c: number) => void;
export const grid_set_cell: (a: number, b: number, c: number, d: number, e: number) => void;
export const grid_set_cell_style: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const grid_set_col_width: (a: number, b: number, c: number) => void;
export const grid_set_default_col_width: (a: number, b: number) => void;
export const grid_set_default_row_height: (a: number, b: number) => void;
export const grid_set_row_height: (a: number, b: number, c: number) => void;
export const grid_set_scroll: (a: number, b: number, c: number) => void;
export const grid_set_viewport: (a: number, b: number, c: number) => void;
export const grid_start_col_resize: (a: number, b: number, c: number) => void;
export const grid_toggle_group: (a: number, b: number) => void;
export const grid_update_col_resize: (a: number, b: number) => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
